function h = h(v_r,r_r,sag)
%H
%    H = H(V_R,R_R,SAG)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    18-Oct-2017 16:46:24

t2 = conj(r_r);
h = [conj(v_r),t2,t2.*(-2.463883587786259e-1)+t2.^2.*conj(sag)+1.71e2./1.0e2];
