function jF = jF(a_r,v_r,r_r,sag,phi,the,psi,dphi,dthe,dpsi,dt)
%JF
%    JF = JF(A_R,V_R,R_R,SAG,PHI,THE,PSI,DPHI,DTHE,DPSI,DT)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    16-Oct-2017 09:01:10

jF = reshape([1.0,conj(dt),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
