function jH = jH(v_r,r_r,sag)
%JH
%    JH = JH(V_R,R_R,SAG)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    18-Oct-2017 16:58:58

t2 = conj(r_r);
jH = reshape([1.0,0.0,0.0,0.0,1.0,t2.*conj(sag).*2.0-2.463883587786259e-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2.^2],[3,6]);
