function rotA = rotAcc(aX,aY,aZ,phi,the,psi)
%ROTACC
%    ROTA = ROTACC(AX,AY,AZ,PHI,PSI,THE)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    21-Sep-2017 13:23:49

t2 = sin(phi);
t3 = sin(psi);
t4 = cos(phi);
t5 = cos(psi);
t6 = sin(the);
t7 = cos(the);
rotA = [-aY.*(t3.*t4-t2.*t5.*t6)+aZ.*(t2.*t3+t4.*t5.*t6)+aX.*t5.*t7;aY.*(t4.*t5+t2.*t3.*t6)-aZ.*(t2.*t5-t3.*t4.*t6)+aX.*t3.*t7;-aX.*t6+aY.*t2.*t7+aZ.*t4.*t7];
